// import './instance/index'
// import './lifecycle/index'
// import './data-binding/index'
// import './computed/index'
// import './directive/index'
// import './directive/define'
// import './directive/v-model'
// import './directive/feature'
import './directive/render'
